# Generated by Django 4.2.29 on 2026-03-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sport', models.CharField(max_length=64)),
                ('class_level', models.CharField(max_length=32)),
                ('fitness_score', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('Cleared', 'Cleared'), ('Pending', 'Pending'), ('Restricted', 'Restricted')], max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fitness_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrendEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=16)),
                ('average_fitness', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
